# Generated by Django 3.0.6 on 2020-06-06 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardModels',
            new_name='BoardModel',
        ),
    ]
